### PR TITLE
fix(api): updated to have proper resource naming

### PR DESCRIPTION
**Pull request by Wagan8r**
Fixed the 'sound/sounds' resource to be consistently named 'sounds' per typical REST convention

### CODE REVIEW

**Comment by Felttrip** [comment]
This really should have had more community feedback. What's the point of a benevolent dictator if they make the wrong decision. ☹️

**Comment by Felttrip** [comment]
Also this breaks my bespoke integration, plz major.

**Comment by beverts312** [comment]
@Felttrip

**Comment by awagner23** [comment]
This is a pre-release version, and the mistake needed to be caught before general consumption. You shouldn't build integrations on a 0.x build.

**Pull request merged**
